version: '3.9'
services:
  swadebot.api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    restart: unless-stopped
    networks:
      - swadeBotNet

  swadebot.app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - swadeBotNet

  swadebot.bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./bot:/app
    restart: unless-stopped
    networks:
      - swadeBotNet

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - swadebot.api
      - swadebot.app
      - swadebot.bot
    networks:
      - swadeBotNet

networks:
  swadeBotNet:
